spring:
  application:
    name: garage-service
  datasource:
    username: ${POSTGRESQL_USERNAME}
    url: jdbc:postgresql://${POSTGRESQL_CONTAINER}/${POSTGRESQL_DATABASE_GARAGES}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

API:
  SECRET:
    KEY: "PiotrKania2137"