spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/user/**
          filters:
            - name: RoleFilter

        - id: vehicle-service
          uri: http://vehicle-service:8080
          predicates:
            - Path=/vehicle/**
          filters:
            - name: RoleFilter

        - id: garage-service
          uri: http://garage-service:8080
          predicates:
            - Path=/garage/**,/report/**
          filters:
            - name: RoleFilter

        - id: recommendation-service
          uri: http://recommendation-service:8080
          predicates:
            - Path=/recommendation/**
          filters:
            - name: RoleFilter

        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/notification/**
          filters:
            - name: RoleFilter




jwt:
  secret: ${JWT_SECRET_KEY}



#services:
#  user_service: http://user-service:8080
#  recommendation_service: http://recommendation-service:8080
#  notification_service: http://notification-service:8080
#  garage_service: http://garage-service:8080
#  vehicle_service: http://vehicle-service:8080
